version: '3'



services:

  mysql:

    build:

      context: ./docker/mysql

      args:

        mysql_version: ${MYSQL_VERSION}

    container_name: ${COMPOSE_PROJECT_NAME}-mysql

    environment:

      MYSQL_DATABASE: ${MYSQL_DATABASE}

      MYSQL_USER: ${MYSQL_USER}

      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}


    ports:

      - "3306:3306"

    networks:
     - red1

    restart: always

  
  php:

    build:

      context: ./docker/php

      args:

        php_version: ${PHP_VERSION}

    container_name: ${COMPOSE_PROJECT_NAME}-php

    ports:

      - "${PHP_PORT}:80"

    networks:
     - red1

    volumes:

      - ./www:/var/www/html

    links:

      - mysql


  web:

    build: .

    ports:

      - "5000:5000"
    
    networks:
     - red1

    volumes:

      - .:/code

    environment:

      FLASK_ENV: development

  redis:

    image: "redis:alpine"

  
networks:

  red1:

    driver: bridge

    ipam:

     config:

       - subnet: 10.5.0.0/16

         gateway: 10.5.0.1

         aux_addresses:

          mysql: 10.5.0.5

          php: 10.5.0.6
          
          web: 10.5.0.7
